### ISSUE TITLE
sync gives weird error when not able to clone a repository

### ISSUE THREAD

**Issue by jfrohnhofen** [daedaleanai/dbt#68]
When `dbt sync` clones a git repository without sufficient permissions for the first time, it will get stuck. However, the dependency directory is still created.
Subsequent `dbt sync` attempts will fin the empty directory and treat it as a local module (which is not allowed or dependencies). That results in an unexpected error message.

Fixes:
- git clone should not get stuck, but report an error
- if dbt fails to initialize a dependency it should no leave behind an empty directory

**Comment by ptia** [comment]
I think this also happens for errors when getting tar modules for the first time. If anything goes wrong, the directory is left behind (possibly half-populated), and the same thing happens. As of now, tar errors are pretty hard to come by, but when we enforce the Unix tarball convention (issue https://github.com/daedaleanai/dbt/issues/74), they might start happening more often.

**Comment by ptia** [comment]
Some solutions:
 * add something like cleanUpModule and making sure we call that before any log.Failure in the create*Module() functions
 * add something like createModuleFailure that logs and cleans up, and using that instead of log.Failure
 * make create*Module() return (Module, err) and handle the error and the cleanup somewhere else
The last one seems more go-like and probably better IMO
