### ISSUE TITLE
Feature request: Run a selected set of binaries.

### ISSUE THREAD

**Issue by paulhankin** [daedaleanai/dbt#87]
The request is to add some way to build and run a selected set of binary targets.

The motivation (which depends on https://github.com/daedaleanai/dbt/issues/86) is that it would be very nice to be able to find and run all tests (assuming their names end "Test"). I can kind of do that by using "dbt build ..." and then parsing the output (assuming no failures), but it would be nice to have an extended target syntax, so I could write something like:

    dbt run "**/*Test" cc-toolchain=mytoolchain

or with a regexp that filters targets:

    dbt run ... -target-match ".*Test" cc-toolchain=mytoolchain

The extended target syntax should probably apply everywhere it makes sense, which currently means for "dbt build".

**Comment by jfrohnhofen** [comment]
I think the regexp filtering is better (since it is well defined) than coming up with our own wildcard syntax. Would you expect the regexp to be applied to the whole target path (e.g. foo/bar/BazTest) or only the name (BazTest)? The problem with the former is that there is that targets can be referenced by their relative path or their absolute path. So if only matching the target name is sufficient, I think that will be easier (both to implement and understand as a user)
